FROM openjdk:14-jdk-alpine
RUN addgroup -S community && adduser -S membershipservice -G community
USER membershipservice:community
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=DOCKER", "-jar","/app.jar"]
